"""initial migration

Revision ID: 413244c14ee
Revises: None
Create Date: 2015-09-15 00:50:22.590027

"""

# revision identifiers, used by Alembic.
revision = '413244c14ee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    ### end Alembic commands ###
